# library(datasets)
# head(iris)
install.packages('ggplot2', dep = TRUE, repos = "http://cran.us.r-project.org")
library(ggplot2)
# ggplot(iris, aes(Petal.Length, Petal.Width, color = Species)) + geom_point()
dataset = read.csv("C:/Users/developer/Desktop/cezdev/libs/c3dclassessdk/ccore/calgorithms/cprinciplecomponentanalysis/iris-2d.dat")
set.seed(20)
dataset
Cluster <- kmeans(dataset, 3, nstart = 20)
Cluster$cluster <- as.factor(Cluster$cluster)
png("myplot.png")
ggplot(dataset, aes(Z0, Z1, color = Cluster$cluster)) + geom_point()
dev.off()
